// export var BASE_URL = 'https://hexeros.com/dev/godafly/api/V1/';
export var BASE_URL = 'https://godafly.info/api/V1/';

export const ApiEndpoint = {
  // API Endpoints
  SIGN_UP: BASE_URL + 'signup',
  LOGIN: BASE_URL + 'login',
  CHECK_SOCIAL: BASE_URL + 'check_social_ability',
  FORGOT_PASSWORD: BASE_URL + 'forgot_password',
  USER_LOGOUT: BASE_URL + 'user/logout',
  USER_DELETE: BASE_URL + 'user/delete_account',
  SETUP_PROFILE: BASE_URL + 'user/setup_profile',
  EDIT_PROFILE: BASE_URL + 'user/edit_profile',
  DELETE_IMAGES: BASE_URL + 'user/delete_user_image',
  GET_PROFILE: BASE_URL + 'user/getProfile',
  CHANGE_PASSWORD: BASE_URL + 'user/change_password',
  UPDATE_NOTIFICATION_STATUS: BASE_URL + 'user/update_notification_status',
  GET_INTEREST: BASE_URL + 'get_interest',
  GET_NOTIFICATION: BASE_URL + 'get_notification',
  SAVE_TRAVELS: BASE_URL + 'travel_save_list',
  DELETE_TRAVEL: BASE_URL + 'delete_travel',
  V_CHECKER: BASE_URL + 'version_checker',
  TRAVELS_HISTORY: BASE_URL + 'travel_history',
  SEARCH_B_FLIGHT: BASE_URL + 'search_user_by_flight_number',
  SAVE_B_FLIGHT: BASE_URL + 'save_search_user_by_flight_number',
  SEARCH_B_LAYOVER: BASE_URL + 'search_user_by_layover',
  SAVE_B_LAYOVER: BASE_URL + 'save_search_user_by_layover',
  GET_CITIES: BASE_URL + 'get_cities',
  GET_AIRPORTS: BASE_URL + 'get_airports',
  USER_DETAIL: BASE_URL + 'user_detail',
  SEND_CHAT_REQUEST: BASE_URL + 'send_chat_request',
  F_REQUEST_LIST: BASE_URL + 'friend_request_list',
  CHAT_THREADS: BASE_URL + 'threads',
  A_R_F_REQUEST: BASE_URL + 'accept_reject_friend_request',
  DELETE_CHAT_THREAD: BASE_URL + 'delete_chat_detail',
  DELETE_CHAT: BASE_URL + 'delete_chat',
  CHAT_HISTORY: BASE_URL + 'chat_history',
  SEND_CHAT: BASE_URL + 'chat',
  REPORT_USER: BASE_URL + 'report_user',
};

export const ApiKeys = {
  DEVICE_ID: 'device_id',
  DEVICE_TYPE: 'device_type',
  PUSH_TOKEN: 'push_token',
  NAME: 'name',
  F_NAME: 'first_name',
  L_NAME: 'last_name',
  COUNTRY_CODE: 'country_code',
  COUNTRY_INITIAL_CODE: 'country_initial_code',
  MOBILE: 'mobile',
  REGISTER_WITH: 'register_with',
  S_USER_ID: 'social_user_id',
  S_ID: 'social_id',
  EMAIL: 'email',
  PASSWORD: 'password',
  PROFILE_IMG: 'profile_image',
  DOB: 'dob',
  BIO: 'bio',
  INTEREST: 'interest',
  USER_IMG: 'user_image',
  O_PASSWORD: 'opassword',
  N_PASSWORD: 'npassword',
  C_PASSWORD: 'cpassword',
  STATUS: 'status',
  DATE: 'date',
  FLIGHT_NUMBER: 'flight_number',
  CARRIER_CODE: 'carrier_code',
  START_IATA_C: 'start_iata_code',
  START_T_Q: 'start_timings_qualifier',
  START_T_V: 'start_timings_value',
  END_IATA_C: 'end_iata_code',
  END_T_Q: 'end_timings_qualifier',
  END_T_V: 'end_timings_value',
  CITY_ID: 'city_id',
  AIR_ID: 'airport_id',
  ARRI_TIME: 'arrival_time',
  DEPA_TIME: 'departure_time',
  CITY_NAME: 'city_name',
  ID: 'id',
  F_ID: 'friend_id',
  LIMIT: 'limit',
  OFFSET: 'offset',
  VERSION: 'version',
  T_ID: 'threads_id',
  T_USER_ID: 'to_user_id',
  TYPE: 'type',
  MESSAGE: 'message',
  BLOCK_U_ID: 'block_user_id',
  REASON: 'reason',
  DESC: 'description',
};

export const keyPref = {
  USER_DATA: 'USER_DATA',
  FCM_TOKEN: 'FCM_TOKEN',
};
