-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdfqZgE/Gc5qKCsRl
HlQRMh3C0/ZxPb/lEAjQS9H/hCugCgYIKoZIzj0DAQehRANCAATeF22A3RPRIM9E
2WsekIq5+JIPwNnZp1vFocfoFC8fkLGyRH3HHTQJ1S5cFawx6NdUXzfb7lYR8Zed
nHPJnoC7
-----END PRIVATE KEY-----