export const ImageView = {
  splashImg: require('../assets/images/splashImg.png'),
  appLogo: require('../assets/images/appLogo.png'),
  curveImg: require('../assets/images/curveImg.png'),
  show: require('../assets/images/show.png'),
  hide: require('../assets/images/hide.png'),
  apple: require('../assets/images/apple.png'),
  facebook: require('../assets/images/facebook.png'),
  downArrow: require('../assets/images/downArrow.png'),
  forgotPass: require('../assets/images/forgotPass.png'),
  backIcon: require('../assets/images/backIcon.png'),
  profileSecond: require('../assets/images/profileSecond.png'),
  camera: require('../assets/images/camera.png'),
  chooseCamera: require('../assets/images/chooseCamera.png'),
  chooseGallery: require('../assets/images/chooseGallery.png'),
  calendar: require('../assets/images/calendar.png'),
  close: require('../assets/images/close.png'),
  dropDown: require('../assets/images/dropDown.png'),
  addImg: require('../assets/images/addImg.png'),
  closeSecond: require('../assets/images/closeSecond.png'),
  roundUnchecked: require('../assets/images/roundUnchecked.png'),
  roundChecked: require('../assets/images/roundChecked.png'),
  notfication: require('../assets/images/notfication.png'),
  notificationSecond: require('../assets/images/notificationSecond.png'),
  search: require('../assets/images/search.png'),
  searchSecond: require('../assets/images/searchSecond.png'),
  trash: require('../assets/images/trash.png'),
  time: require('../assets/images/time.png'),
  saveProfile: require('../assets/images/saveProfile.png'),
  setting: require('../assets/images/setting.png'),
  editProfile: require('../assets/images/editProfile.png'),
  lock: require('../assets/images/lock.png'),
  notificationSettings: require('../assets/images/notificationSettings.png'),
  logout: require('../assets/images/logout.png'),
  deleteAccount: require('../assets/images/deleteAccount.png'),
  more: require('../assets/images/more.png'),
  report: require('../assets/images/report.png'),
  deleteChat: require('../assets/images/deleteChat.png'),
  roundDotUnchecked: require('../assets/images/roundDotUnchecked.png'),
  roundDotChecked: require('../assets/images/roundDotChecked.png'),
  send: require('../assets/images/send.png'),
  longArrow: require('../assets/images/longArrow.png'),

  home: require('../assets/images/home.png'),
  activeHome: require('../assets/images/activeHome.png'),
  travels: require('../assets/images/travels.png'),
  activeTravels: require('../assets/images/activeTravels.png'),
  searchTab: require('../assets/images/searchTab.png'),
  chat: require('../assets/images/chat.png'),
  activeChat: require('../assets/images/activeChat.png'),
  profile: require('../assets/images/profile.png'),
  activeProfile: require('../assets/images/activeProfile.png'),

  layover_1: require('../assets/randomLayoverImg/layover_1.png'),
  layover_2: require('../assets/randomLayoverImg/layover_2.png'),
  layover_3: require('../assets/randomLayoverImg/layover_3.png'),
  layover_4: require('../assets/randomLayoverImg/layover_4.png'),
  layover_5: require('../assets/randomLayoverImg/layover_5.png'),
  layover_6: require('../assets/randomLayoverImg/layover_6.png'),
  layover_7: require('../assets/randomLayoverImg/layover_7.png'),
  layover_8: require('../assets/randomLayoverImg/layover_8.png'),
  layover_9: require('../assets/randomLayoverImg/layover_9.png'),
  layover_10: require('../assets/randomLayoverImg/layover_10.png'),
  layover_11: require('../assets/randomLayoverImg/layover_11.png'),
  searchLayoverBanner: require('../assets/randomLayoverImg/searchBanner.png'),

  travel_1: require('../assets/randomFlightImg/travel_1.png'),
  travel_2: require('../assets/randomFlightImg/travel_2.png'),
  travel_3: require('../assets/randomFlightImg/travel_3.png'),
  travel_4: require('../assets/randomFlightImg/travel_4.png'),
  travel_5: require('../assets/randomFlightImg/travel_5.png'),
  travel_6: require('../assets/randomFlightImg/travel_6.png'),
  travel_7: require('../assets/randomFlightImg/travel_7.png'),
  travel_8: require('../assets/randomFlightImg/travel_8.png'),
  travel_9: require('../assets/randomFlightImg/travel_9.png'),
  travel_10: require('../assets/randomFlightImg/travel_10.png'),
  travel_11: require('../assets/randomFlightImg/travel_11.png'),
  searchFlightBanner: require('../assets/randomFlightImg/searchBanner.png'),
};
export default {
  ImageView,
};
